name: GitHub Pages

on:
  push:
    branches:
    - master
    paths:
    - docs/**
    - mkdocs.yml
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0 # for the 'Last updated' timestamp
    - run: pip install -r requirements.txt
    - run: mkdocs build
    - uses: actions/upload-pages-artifact@v5
      with:
        path: site
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
    - id: deployment
      uses: actions/deploy-pages@v5
